### PR TITLE
fix: html-webpack-plugin child compiler chunk id

### LINKED ISSUE #55: html-webpack-plugin fails with serve plugin
- Webpack Version: the latest
- Operating System (or Browser): mac os sierra
- Node Version: v8.12.0
- webpack-plugin-serve Version: 0.2.1

### How Do We Reproduce?

https://github.com/TrySound/wp-bug

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

fixes #55. when used in a minimal setup, html-webpack-plugin alters the typical compiler pathways such that `hotBootstrap` is called before a shared chunk variable is set, causing an error in compilation.

We need to add tests to this branch to watch for this as a regression as other similar bugs are fixed in the future. Webpack hooks are brittle, and modifying aspects of a build to overcome its shortcomings is also very brittle.

### CODE REVIEW

**Comment by TrySound** [comment]
Server works for me however seems like regenerator is missing in hmr
image

**Comment by shellscape** [comment]
@pronevich looks like you have a different issue. please post a new issue so we can break that one down based on your config. a minimal reproducible repo would be handy there too.

@TrySound I'll take a look at that

**Comment by shellscape** [comment]
@TrySound using your test repo from #55, I see no such error:

Imgur

**Comment by pronevich** [comment]
@shellscape yeah maybe this is not wps issue, reproducing this fix for react recipe from this repo - all works fine

**Comment by shellscape** [comment]
Great, thanks for confirming. If you all have any other issues, please don't hesitate to open new issues.

**Comment by TrySound** [comment]
Thanks

**Pull request merged**
