### PR TITLE
Attempt to create a working config for custom directories and publicPath

### PR DESCRIPTION
**Pull request by EvHaus**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [x] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

### Please Describe Your Changes

@shellscape Thanks for `webpack-plugin-serve`. It looks amazing, and I can't wait to get it setup in our large application. Unfortunately, we're running into an issue getting migrated over. I'm hoping you'll have a chance to look at this PR which includes a reproducible test case and offer some insights. Maybe this can be used as documentation for users having a similar issue in the future.

The goals:

- Our webpack configs in a dedicated top-level `/webpack` directory. We like this, but it's important to note here as it means paths need to be configured a bit differently
- Our source code is in a folder called `/html/js/` (as opposed to all other examples which use `/src`)
- We use a custom `index.html` file for serving content which exists in `/html/index.html`. This is used both for production and development builds. We don't want `webpack-plugin-serve` to generate its own `index.html` file.
- We want exported webpack bundles to go into `/html/build`, not into a top-level directory
- As a result of all this, we want the main bundle to be served `/html/build/bundle.js`

At the moment, I'm not able to make this work using `webpack-plugin-serve` despite my best efforts. The biggest issues I can't overcome are:

- A new `index.html` is written into `html/build`, instead of a using the existing `/html/index.html`.
- Builds aren't being loaded from where they're being written to.

Currently, we use `webpack-serve` to achieve this and the config for it is:

```
serve: {
		add: (app, middleware, options) => {
			app.use(convert(history()));
		},
		content: path.resolve(__dirname, '..', 'html'),
		devMiddleware: {
			publicPath: '/build/',
		},
	},
```

I think I'm missing an equivalent for that `serve.content` config.

Would you be able to take a look and offer some pointers?

### CODE REVIEW

**Comment by PlayMa256** [comment]
It is not really a wps issue, but i can help you go through it.
Let's go step by step, you said:

> A new index.html is written into html/build, instead of a using the existing /html/index.html.

This is because you are using `HtmlWebpackPlugin`, this plugin will generate an html everytime a build is ran.

> Builds aren't being loaded from where they're being written to.

As you can see here, they are being loaded from where they are ment to be: [image]

**Comment by EvHaus** [comment]
Thank you @PlayMa256. That indeed solves the issue in the PR.

**Comment by PlayMa256** [comment]
No problem! I'm here to help!!

**Comment by shellscape** [comment]
Can we update the docs to help with this kind of thing moving forward?

**Comment by PlayMa256** [comment]
For sure. I'll update that.

**Pull request closed without merging**
