### PR TITLE
fix: recognize pfx format for http2 options

### PR DESCRIPTION
**Pull request by Evalon**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no (if not misconfigured)

### Please Describe Your Changes

This PR fixes the problem when pfx field is ignored in http2 options. In fact the plugin couldn't create the server properly in this case.

There is two formats that's natively supported by createSecureServer (tls.createSecureContext): pfx and pem. 
So we should check for both of them and use createSecureServer instead of createServer when pfx inside http2 is set.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for opening a pull request. You'll need to add a test for this before we'll be able to accept it.

**Comment by shellscape** [comment]
@Evalon quick ping. since we're at 30 days without a reply to my last comment, please let me know if you're interested in adding tests for your change. If not, or if we don't hear from you in the next day or so, we'll have to decline your PR and that would be a bummer.

**Comment by Evalon** [comment]
Sorry for such a delay. I got COVID and was sick for several weeks. I will do this during the weekend if it's okay for you to wait.

**Comment by shellscape** [comment]
Oh man! I hope you're feeling much better! We'll keep this open for you of course.

**Comment by Evalon** [comment]
tests added

**Comment by shellscape** [comment]
Look great 
thanks!

**Pull request merged**
