### PR TITLE
fix(ansi): add ansi support for react-refresh-webpack-plugin

### PR DESCRIPTION
**Pull request by PlayMa256**
This PR contains:

- [X] bugfix
- [X] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [ ] no

If yes, please describe the breakage.

### Please Describe Your Changes
Based on https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/74 adding support for the ansi error messages!

### CODE REVIEW

**Comment by pmmmwh** [comment]
Is it possible to defer the ANSI to HTML transform to the client side (i.e. `./lib/client/overlays/status.js`)? A good reason for that is to allow custom syntax-highlighting theming for third-parties (like framework-specific error overlays) - for example, to reset the `background` color of the message to `transparent` so that there won't be a black background behind the text.

**Comment by shellscape** [comment]
> A good reason for that is to allow custom syntax-highlighting theming for third-parties (like framework-specific error overlays)

This is exactly why I chose to strip ansi characters from the outgoing websocket message. That, and I didn't want our dialogs to be beholden to whatever format webpack happened to put in place. If an undesirable update happened then we'd be forced to parse more output, and I wanted to avoid that. 

Do we have screenshots on the before and after of this change, and what problem it solves?

**Comment by pmmmwh** [comment]
> I think a better route here would be highlighting as appropriate on the client-side. That would give other overlay displayers the ability to style as they see fit, and we can choose an appropriate lib for our overlays on the client.
>
> So, let's pivot this PR to coloring/highlighting syntax on the client, and leave the ansi stripping in place.

I agree. I've investigated the problem further, and I've come to realize that the predominant cause of ANSI error output is from `@babel/code-frame`, which will be used whenever `babel-loader` is used. It is a custom format output that is not purely JavaScript, but `highlight.js` seems to be able to parse that (Assumption only, because the Babel website uses this).

**Comment by PlayMa256** [comment]
This was a really good discussion!!! Ok @shellscape i’lol be moving towards coloring on the Client side rather than giving the code-frames from Babel directly to the client!!!

**Comment by shellscape** [comment]
@PlayMa256 going to close this one for now. Please let me know if we need to reopen at a point.

**Pull request closed without merging**
