### PR TITLE
refactor: remove old node fix

### PR DESCRIPTION
**Pull request by TrySound**
This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

Only node 10 is supported for a long time. The fix for node < 10 can be
removed.

### CODE REVIEW

**Review by shellscape — APPROVED** [review]

**Review by bebraw — APPROVED** [review]

**Comment by shellscape** [comment]
@TrySound please fix the commit message

**Comment by shellscape** [comment]
@TrySound couple of failures in CI

**Comment by TrySound** [comment]
Hm.. So the fix actually necessary?

**Comment by shellscape** [comment]
Not sure. Does it fail locally on Node 14? If it does, could be a regression in 14.

**Comment by TrySound** [comment]
Hm... all good locally

**Comment by shellscape** [comment]
give CI a rerun to see if that fixes it

**Pull request merged**
