### PR TITLE
Allow user to override publicPath setting.

### PR DESCRIPTION
**Pull request by nicksrandall**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

This allows users to use Webpack's `auto` option for publicPath and still set a public path for the dev server.

### CODE REVIEW

**Comment by shellscape** [comment]
I'll consider this PR once tests and documentation have been added.

**Comment by nicksrandall** [comment]
@shellscape docs and tests have been added.

**Comment by shellscape** [comment]
I'll be giving open source some love early next week.

**Comment by nicksrandall** [comment]
@shellscape just following up. Any change this can get reviewed?

**Comment by ggat** [comment]
Related to https://github.com/shellscape/webpack-plugin-serve/issues/216#issue-818600299 to some degree

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
